name: CI

on:
  workflow_dispatch:

jobs:
  regression:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

  publish:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
    needs: regression
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create public directory
        run: mkdir -p public/gouda

      - name: Copy test results
        run: cp -R playwright-report/* public/gouda/

      - name: Upload public directory
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gouda
          path: public
          retention-days: 5
